---
title: "Regression"
author: "Audrey Garcia"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
library(tidyverse)
library(mlr3)
```


```{r}
amazon_purchases <- read_csv("ucla-stats-101-c-fall-2025-regression/amazon-purchases.csv")
fields <- read_csv("ucla-stats-101-c-fall-2025-regression/fields.csv")
survey_train_test <- read_csv("ucla-stats-101-c-fall-2025-regression/survey_train_test.csv")
```

```{r}
# Problem description says:
# "removed all information from the test data that wouldn't be known at sign-up (you only have ResponseID, Gender, and state)"
# but he didn't...
# so I did here


survey <- survey_train_test |>
  select(Survey.ResponseID, Q.demos.gender, Q.demos.state, Q.amazon.use.hh.size.num, test) |>
  mutate(Q.demos.gender = as.factor(Q.demos.gender)) |> 
  mutate(Q.demos.state = as.factor(Q.demos.state)) |>
  rename(Gender = Q.demos.gender, State = Q.demos.state, HHSize = Q.amazon.use.hh.size.num)
```

```{r}
amazon <- amazon_purchases |>
  rename(Survey.ResponseID = `Survey ResponseID`)
fulldata <- left_join(amazon, survey, by = "Survey.ResponseID")

training <- fulldata |>
  filter(test == FALSE)
testing <- fulldata |>
  filter(test == TRUE)
```

```{r}

```

